format_version: 10
pipelines:
  Test1:
    group: AT20group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH:
    secure_variables:
      SONAR_TOKEN: AES:DKno0ZKyMLbK42PVqz3vQw==:wHdzKXg5j+LhcZgl3EhrcA==
    materials:
      git-3bef966:
        git: https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE.git
        username: daniish77
        shallow_clone: false
        auto_update: true
        branch: task11-dc
        encrypted_password: AES:L0A67qe/6sGlax8rPQJcJQ==:WGhnuvjwdkNCIcjOUtJ+XA==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources :
            - ubuntu
            tasks:
            - script : |
                npm install
                npm run test
            artifacts :
            - build:
                source: AT20_CONVERT_SERVICE/test/report/report.html
                destination: html_report



