format_version: 10
pipelines:
  Test:
    group: AT20-czn
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GIT_COMMIT_HASH: 1.2
    secure_variables:
      SONAR_TOKEN: AES:jBS5s9YWkE5zshtYA+za6A==:LBjKeAThwwf9xZAPBVMwmmW6UbaI8mHluXWxEEWEQaUW/bV+MqBPGo2Lcs2VJXlM
      DOCKER_PASS: AES:9iJXyHiv1e+AK3eDD0h9Pw==:EWoP0YfngEtsXgMUuyVe4A==
    materials:
      git-dbfb6af:
        git: https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE.git
        username: carolinazegarra01
        shallow_clone: false
        auto_update: true
        branch: task14-czn
        encrypted_password: AES:YglD8hhgJFuJMXQUwtXSVw==:gCQ0ar8k+rZ8llR0tOdQHA==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            resources :
            - ubuntu
            tasks:
            - script: |
                git rev-parse --short HEAD > gitCommit.txt
                npm install --save-dev ts-jest
                npm install --save-dev @types/jest
                npx jest
            artifacts:
            - build:
                source: test/report/report.html
                destination: html_report
            - build:
                source: Dockerfile
            - build:
                source: docker-compose-czn.yaml
            - build: 
                source: .env
            - build:
                source: gitCommit.txt
    - code_inspection:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            resources :
            - ubuntu
            tasks:
            - script: |
                /godata/.sonar/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner \
                    -Dsonar.organization=at20-czn \
                    -Dsonar.projectKey=at20-czn \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=https://sonarcloud.io
    - PackageAndPublish:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker:
            timeout: 0
            resources :
            - docker
            tasks:
            - fetch:
                is_file: false
                source: ./
                stage: Test
                job: unit-test
                run_if: passed
            - script: |
                docker build -t at20_convert_service .
                docker login -u carolina01 --password-stdin <<< ${DOCKER_PASS}
                docker tag at20_convert_service carolina01/at20_convert_service:$(cat gitCommit.txt)
                docker push carolina01/at20_convert_service:$(cat gitCommit.txt)
            artifacts:
              - build:
                  source: docker-compose-czn.yaml
              - build: 
                  source: .env
  Acceptance:
    group: AT20-czn
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      TARGET_HOST: 192.168.0.18
    materials:
      Test:
        pipeline: Test
        stage: PackageAndPublish
    stages:
    - DeployToDev:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          smoke-test:
            timeout: 0
            resources :
            - docker
            tasks:
            - fetch:
                pipeline: Test
                stage: Test
                job: unit-test
                source: gitCommit.txt
                is_file: true
                run_if: passed
            - fetch: 
                pipeline: Test
                stage: PackageAndPublish
                job: docker
                source: docker-compose-czn.yaml
                is_file: true
                run_if: passed
            - fetch: 
                pipeline: Test
                stage: PackageAndPublish
                job: docker
                source: .env
                is_file: true
                run_if: passed
            - script: |
                export TAG_VERSION=$(cat gitCommit.txt) && docker-compose -f docker-compose-czn.yaml up -d
  Capacity:
    group: AT20-czn
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      TARGET_HOST: 192.168.0.18
    materials:
      Acceptance:
        pipeline: Acceptance
        stage: DeployToDev
    stages:
    - DeployToAuto:
        fetch_materials: false
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          capacity-test:
            timeout: 0
            resources :
            - docker
            tasks:
            - fetch:
                pipeline: Acceptance
                stage: DeployToDev
                job: smoke-test
                source: gitCommit.txt
                is_file: true
                run_if: passed
            - fetch: 
                pipeline: Acceptance
                stage: DeployToDev
                job: smoke-test
                source: docker-compose-czn.yaml
                is_file: true
                run_if: passed
            - fetch: 
                pipeline: Acceptance
                stage: DeployToDev
                job: smoke-test
                source: .env
                is_file: true
                run_if: passed
            - script: |
                export TAG_VERSION=$(cat gitCommit.txt) && DOCKER_HOST=ssh://$TARGET_HOST docker-compose -f docker-compose-czn.yaml up -d
