format_version: 10
pipelines:
  Test1:
    group: AT20group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-3bef966:
        git: https://github.com/AT20-DevOps/AT20_CONVERT_SERVICE.git
        username: daniish77
        shallow_clone: false
        auto_update: true
        branch: task9-dc
        encrypted_password: AES:L0A67qe/6sGlax8rPQJcJQ==:WGhnuvjwdkNCIcjOUtJ+XA==
    stages:
    - Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Hello
                - World
                command: echo
                run_if: passed
          code_coverage:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -la
                command: ls
                run_if: passed
    - code-inspection:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          sonar:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - sonar-scanner command
                command: echo
                run_if: passed
