pipeline{
    agent any
    stages {
        stage("Test"){
            agent { docker 'node:18-alpine3.16'}
            steps {
                sh 'apk add --no-cache ffmpeg'
                sh 'npm install --save-dev ts-jest'
                sh 'npm i --save-dev @types/jest'
                sh 'npm run test'
            }
        }
    }
}