pipeline{
    agent any
    environment {
        DOCKER_PASS = credentials('docker_pass')
        SONAR_TOKEN = credentials('sonar_token')
        TARGET_HOST = '192.168.0.151'
        GIT_COMMIT_HASH = sh (script: "git rev-parse --short HEAD", returnStdout: true)
    }
    stages {
        stage("Test"){
            agent { docker 'node:18-alpine3.16'}
            steps {
                sh 'npm install'
                sh 'npm i --save-dev @types/jest'
                sh 'npm run test'
            }
            post{
                always{
                    archiveArtifacts artifacts: 'test/report/report.html', followSymlinks: false
                }
            }
        }
        stage('CodeInspection'){
            agent{
                docker 'sonarsource/sonar-scanner-cli'
            }
            steps{
                withSonarQubeEnv('sonar_scanner'){
                    sh 'sonar-scanner \
                        -Dsonar.organization=at20-dc \
                        -Dsonar.projectKey=convert-service-dc \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io'
                }
            }
        }
        stage('Quality gate'){
            steps{
                timeout(time: 3, unit: 'MINUTES') {
                    script{
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                        error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }
        stage('Package'){
            steps{
                sh'docker build -t at20_convert_service .'
            }
        }
        stage('Publish'){
            steps{
                sh 'docker login -u daniish77 -p ${DOCKER_PASS}'
                sh 'docker tag at20_convert_service daniish77/at20_convert_service:${GIT_COMMIT_HASH}'
                sh 'docker push daniish77/at20_convert_service:${GIT_COMMIT_HASH}'
            }

        }
        stage('DeployToDev'){
            steps{
                sh 'export TAG_VERSION=${GIT_COMMIT_HASH} && docker-compose -f docker-compose.dc.yaml up -d'
                sh 'echo command to run smoke test'
            }
        }
        stage('DeployToAuto') {
            steps {
                sh 'export TAG_VERSION=${GIT_COMMIT_HASH} && DOCKER_HOST=ssh://$TARGET_HOST docker-compose -f docker-compose.dc.yaml up -d'
                sh 'echo command to run automation tests'
            }
        }
    }
    post{
        always{
            sh 'docker image prune -a -f'
            emailext (
                    body: 'Pipeline for ${JOB_NAME} on build ${BUILD_NUMBER} has been executed ${BUILD_STATUS}, for details go to ${BUILD_URL}',
                    subject: 'COnverter service build was executed ${BUILD_STATUS}',
                    to: 'daniish77@gmail.com',
                    attachLog: true
            )
        }
    }

}